### ISSUE TITLE
Change example in linear_programming.py

### ISSUE THREAD

**Issue by titipata** [daniel-acuna/reviewer_assignment#18]
The example in `linear_programming.py` is not feasible, we should come up with example that has solution. Also add documentation to say that `A` is `coo_matrix` input.

**Comment by daniel-acuna** [comment]
I’ll add this one

http://www.vitutor.com/alg/linear_programming/example_programming.html

On Feb 11, 2015, at 12:03 PM, Titipat Achakulvisut <notifications@github.com<mailto:notifications@github.com>> wrote:

The example in linear_programming.py is not feasible, we should come up with example that has solution. Also add documentation to say that A is coo_matrix input.

**Comment by daniel-acuna** [comment]
Well, I couldn’t test it on my mac because ortools cannot be installed there... See issue #20

On Feb 11, 2015, at 12:08 PM, Daniel Acuna <daniel.acuna@northwestern.edu<mailto:daniel.acuna@northwestern.edu>> wrote:

I’ll add this one

http://www.vitutor.com/alg/linear_programming/example_programming.html

On Feb 11, 2015, at 12:03 PM, Titipat Achakulvisut <notifications@github.com<mailto:notifications@github.com>> wrote:

The example in linear_programming.py is not feasible, we should come up with example that has solution. Also add documentation to say that A is coo_matrix input.
